### PR TITLE
Update Cheatsheet.md

### PR DESCRIPTION
**Pull request by Cor-Cordium**
file extension definition

### CODE REVIEW

**Comment by rochelleterman** [comment]
Who is this? I don't see this github username on the survey responses. Please let me know who you are, especially if you're taking this course for credit.

**Comment by Cor-Cordium** [comment]
Hi, Rochelle. This is Cory, and I submitted a survey response during
InstallFest... :-/ I swear!

**Comment by Cor-Cordium** [comment]
Maybe I misspelled it on the survey?

**Comment by rochelleterman** [comment]
Hi -

Yep I got it, deleted my comment when I saw it! Sorry!

Rochelle

On Tue, Sep 15, 2015 at 2:55 PM, Cor-Cordium notifications@github.com
wrote:

> Hi, Rochelle. This is Cory, and I submitted a survey response during
> InstallFest... :-/ I swear!
> 
> On Tuesday, September 15, 2015, Rochelle Terman notifications@github.com
> wrote:
> 
> > Who is this? I don't see this github username on the survey responses.
> > Please let me know who you are, especially if you're taking this course
> > for
> > credit.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/rochelleterman/PS239T/pull/48#issuecomment-140556969
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rochelleterman/PS239T/pull/48#issuecomment-140557844.

## 

Rochelle Terman
Ph.D. Candidate, Political Science, University of California Berkeley

email: rterman@gmail.com
phone: +1 (510) 326-3644
www.rochelleterman.com

**Comment by Cor-Cordium** [comment]
_thumbs up_ thanks!

**Pull request merged**
